# Generated by Django 4.2.2 on 2023-06-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyIdentity', models.AutoField(auto_created=True, db_column='CompanyIdentity', primary_key=True, serialize=False)),
                ('CompanyName', models.TextField()),
                ('CompanyEmail', models.TextField()),
                ('CompanyTel', models.TextField()),
                ('CompanyContactPerson', models.TextField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('DivisionIdentity', models.AutoField(auto_created=True, db_column='DivisionIdentity', primary_key=True, serialize=False)),
                ('DivisionName', models.TextField()),
                ('CompanyIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.company')),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('StaffIdentity', models.AutoField(auto_created=True, db_column='StaffIdentity', primary_key=True, serialize=False)),
                ('StaffNo', models.TextField()),
                ('StaffName', models.TextField()),
                ('StaffIDNo', models.TextField()),
                ('Email', models.TextField()),
                ('Employed', models.BooleanField()),
                ('CompanyIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.company')),
                ('DivisionIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.division')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('SubscriptionID', models.AutoField(auto_created=True, db_column='SubscriptionID', primary_key=True, serialize=False)),
                ('SubscriptionKey', models.TextField()),
                ('SubscriptionStartDate', models.DateField()),
                ('SubscriptionEndDate', models.DateField()),
                ('CompanyIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.company')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='ProcessedLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WagemasterLeaveID', models.IntegerField()),
                ('LeaveType', models.TextField()),
                ('StartDate', models.DateField()),
                ('StopDate', models.DateField()),
                ('Approved', models.BooleanField()),
                ('NotApproved', models.BooleanField()),
                ('Taken', models.BooleanField()),
                ('StaffIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.employee')),
            ],
            options={
                'db_table': 'processedleave',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualBfwd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AnnualCfwd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Taken', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Absence', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OffsBfwd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OffsCfwd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MaternityBfwd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MaternityCfwd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SickFull', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SickHalf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StaffIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.employee')),
            ],
            options={
                'db_table': 'leavebalance',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveApplicationIdentity', models.IntegerField()),
                ('LeaveType', models.TextField()),
                ('StartDate', models.DateField()),
                ('StopDate', models.DateField()),
                ('StaffIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.employee')),
            ],
            options={
                'db_table': 'leaveapplication',
            },
        ),
    ]
