# Generated by Django 4.2.2 on 2023-06-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
