# Generated by Django 4.2.2 on 2023-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0002_user_is_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
