# Generated by Django 4.2.2 on 2023-06-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0003_client_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_person',
            new_name='ClientContactPerson',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='company_email',
            new_name='ClientEmail',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='ClientName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='tel',
            new_name='ClientTel',
        ),
    ]
