# Generated by Django 4.2.2 on 2023-06-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0004_rename_contact_person_client_clientcontactperson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='User',
        ),
    ]
