# Generated by Django 4.2.2 on 2023-06-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0005_rename_user_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='User',
            new_name='Username',
        ),
    ]
