# Generated by Django 4.2.2 on 2023-06-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0006_rename_user_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Username',
        ),
        migrations.AddField(
            model_name='client',
            name='ClientUserID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
