# Generated by Django 4.2.2 on 2023-06-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0007_remove_client_username_client_clientuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ClientIdentity',
            field=models.ForeignKey(db_column='ClientIdentity', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='wagemaster_online.client'),
        ),
    ]
