# Generated by Django 4.2.2 on 2023-06-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0008_alter_company_clientidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionDatePaid',
            field=models.DateField(null=True),
        ),
    ]
