# Generated by Django 4.2.2 on 2023-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0011_alter_subscription_subscriptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Maximum_Employees',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionActive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionDatePaid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionKey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
