# Generated by Django 4.2.2 on 2023-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0012_alter_subscription_maximum_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Maximum_Employees',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionActive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
