# Generated by Django 4.2.2 on 2023-06-28 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0013_alter_subscription_maximum_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ClientUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
