# Generated by Django 4.2.2 on 2023-07-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0014_alter_client_clientuserid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='Maximum_Employees',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionActive',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionDatePaid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionEndDate',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionStartDate',
        ),
    ]
