# Generated by Django 4.2.2 on 2023-07-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0015_remove_subscription_maximum_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionKey',
        ),
    ]
