# Generated by Django 4.2.2 on 2023-07-01 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0018_remove_subscription_companyidentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='CompanyIdentity',
            field=models.ForeignKey(db_column='CompanyIdentity', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='wagemaster_online.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='Maximum_Employees',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionDatePaid',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionEndDate',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionStartDate',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
    ]
