# Generated by Django 4.2.2 on 2023-07-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0019_subscription_companyidentity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='CompanyIdentity',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='Maximum_Employees',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionActive',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionDatePaid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionEndDate',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionKey',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionStartDate',
        ),
    ]
