# Generated by Django 4.2.2 on 2023-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0021_subscription_companyidentity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionDatePaid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
