# Generated by Django 4.2.2 on 2023-07-01 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0022_alter_subscription_subscriptiondatepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionDatePaid',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
    ]
