# Generated by Django 4.2.2 on 2023-07-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0024_alter_subscription_subscriptionactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionActive',
        ),
    ]
