# Generated by Django 4.2.2 on 2023-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0025_remove_subscription_subscriptionactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionActive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
