# Generated by Django 4.2.2 on 2023-07-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0026_subscription_subscriptionactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionActive',
        ),
        migrations.AddField(
            model_name='subscription',
            name='SubscriptionStatus',
            field=models.TextField(default='Pending'),
        ),
    ]
