# Generated by Django 4.2.2 on 2023-07-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0027_remove_subscription_subscriptionactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='SubscriptionDatePaid',
            new_name='SubscriptionActionDate',
        ),
    ]
