# Generated by Django 4.2.2 on 2023-12-10 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0031_alter_client_clientuserid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ClientUserID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_administrator',
        ),
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Client'), (3, 'Supervisor'), (4, 'Employee')], default=4),
        ),
    ]
