# Generated by Django 4.2.2 on 2023-12-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0034_extendedgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedgroup',
            name='client_groups',
            field=models.ManyToManyField(blank=True, to='wagemaster_online.clientgroup'),
        ),
    ]
