# Generated by Django 4.2.2 on 2024-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0035_extendedgroup_client_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='SubscriptionKey',
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='division',
            name='DivisionID',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyEmail',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyTel',
            field=models.TextField(max_length=255),
        ),
    ]
