# Generated by Django 4.2.2 on 2024-03-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0036_remove_subscription_subscriptionkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='division',
            name='DivisionID',
        ),
        migrations.AddField(
            model_name='company',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='division',
            name='CompanyKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='division',
            name='DivisionKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='employee',
            name='EmployeeKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='employee',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='EmployeeKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='EmployeeKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processedleave',
            name='EmployeeKey',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='processedleave',
            name='needs_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='CompanyKey',
            field=models.TextField(default='n/a'),
        ),
    ]
