# Generated by Django 4.2.2 on 2024-03-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0037_synctable_remove_division_divisionid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('SupervisorIdentity', models.AutoField(auto_created=True, db_column='SupervisorIdentity', primary_key=True, serialize=False)),
                ('SupervisorName', models.TextField()),
                ('Email', models.TextField()),
                ('SupervisorTel', models.TextField(max_length=255)),
                ('CompanyIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.company')),
            ],
            options={
                'db_table': 'supervisor',
            },
        ),
    ]
