# Generated by Django 4.2.2 on 2024-03-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0040_alter_employee_user_alter_supervisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='CompanyIdentity',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='wagemaster_online.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ClientEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='division',
            name='DivisionName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='StaffIDNo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='StaffName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='StaffNo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='SupervisorName',
            field=models.CharField(max_length=255),
        ),
    ]
