# Generated by Django 4.2.2 on 2024-03-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0043_alter_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='wagemaster_online.client'),
        ),
    ]
