# Generated by Django 4.2.2 on 2024-03-15 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0045_alter_supervisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='client',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='ClientIdentity',
            field=models.ForeignKey(db_column='ClientIdentity', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='wagemaster_online.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
