# Generated by Django 4.2.11 on 2024-03-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0047_remove_leavebalance_staffidentity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='CompanyIdentity',
            field=models.ForeignKey(db_column='CompanyIdentity', on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='CompanyIdentity',
            field=models.ForeignKey(db_column='CompanyIdentity', on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DivisionIdentity',
            field=models.ForeignKey(db_column='DivisionIdentity', on_delete=django.db.models.deletion.CASCADE, to='wagemaster_online.division'),
        ),
    ]
