# Generated by Django 4.2.11 on 2024-03-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagemaster_online', '0048_alter_division_companyidentity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='StaffIDNo',
        ),
    ]
